# Generated by Django 2.2.4 on 2021-04-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('Link', models.TextField(max_length=100)),
                ('Duration', models.TimeField()),
            ],
        ),
    ]
