# Generated by Django 2.2.4 on 2021-04-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20210410_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='Link',
            field=models.URLField(max_length=100),
        ),
    ]
