# Generated by Django 2.2.4 on 2021-04-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20210410_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='keyword',
            field=models.TextField(default='C++'),
        ),
    ]
