# Generated by Django 2.2.4 on 2021-04-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_base_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='Duration',
            field=models.TextField(),
        ),
    ]
