# Generated by Django 2.2.4 on 2021-04-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20210410_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='Duration',
            field=models.DurationField(),
        ),
    ]
