# Generated by Django 2.2.4 on 2021-04-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20210410_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='KeyDuration',
            field=models.IntegerField(default=1),
        ),
    ]
